#!/bin/sh /etc/rc.common

. /lib/functions.sh

START=19
USE_PROCD=1

PROG=/root/chinadns
CHNLIST=/root/config/china.list

start_service() {
	procd_open_instance
	procd_set_param command $PROG -p 2053 -c $CHNLIST -v
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param user root
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	sleep 1s
	start
}
