#!/bin/sh /etc/rc.common

. /lib/functions.sh

START=19
USE_PROCD=1
#PROCD_DEBUG=1

CONF=/root/config/v2ray.json
PROG=/root/v2ray/v2ray
ASSLOC=/root/v2ray

config_load "v2ray"

start_service() {
	procd_open_instance
	procd_set_param command $PROG -config $CONF
	procd_set_param env V2RAY_LOCATION_ASSET=$ASSLOC
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param user root
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	sleep 2s
	start
}
